services:
  postgres:
    image: postgres:15
    container_name: ding-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - ding-dev-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ding-backend-dev
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_AUTH=${NEO4J_AUTH}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_started
      neo4j:
        condition: service_started
    networks:
      - ding-dev-network
    stdin_open: true
    tty: true
    # Generate Prisma client and start in development mode
    command: sh -c "pnpm prisma generate && pnpm run start:dev"

  frontend:
    container_name: ding-frontend-dev
    build:
      context: ../Ding-Platform-Frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ../Ding-Platform-Frontend:/app
      - /app/node_modules
  neo4j:
    image: neo4j:latest
    container_name: ding-neo4j-dev
    restart: always
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data_dev:/data
    networks:
      - ding-dev-network

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: ding-prisma-studio-dev
    restart: always
    ports:
      - '5555:5555'
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - ding-dev-network
    command: sh -c "pnpm prisma generate && npx prisma studio --hostname 0.0.0.0 --port 5555"

volumes:
  pgdata_dev:
  neo4j_data_dev:

networks:
  ding-dev-network:
    driver: bridge