export const PROFILE_CONSTANTS = {
  // File Upload
  UPLOAD: {
    MAX_PROFILE_PICTURE_SIZE: 5 * 1024 * 1024, // 5MB
    MAX_COVER_PHOTO_SIZE: 10 * 1024 * 1024, // 10MB
    ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    PROFILE_PICTURE_DIMENSIONS: {
      WIDTH: 400,
      HEIGHT: 400,
    },
    COVER_PHOTO_DIMENSIONS: {
      WIDTH: 1200,
      HEIGHT: 400,
    },
  },

  // Field Limits
  FIELDS: {
    BIO_MAX_LENGTH: 500,
    LOCATION_MAX_LENGTH: 100,
    WEBSITE_MAX_LENGTH: 200,
    PHONE_MAX_LENGTH: 20,
  },

  // Privacy Settings
  PRIVACY: {
    DEFAULT_PROFILE_VISIBILITY: 'FRIENDS',
    DEFAULT_POSTS_VISIBILITY: 'FRIENDS',
    DEFAULT_FRIENDS_VISIBILITY: 'FRIENDS',
    DEFAULT_BIO_VISIBILITY: 'FRIENDS',
    DEFAULT_EMAIL_VISIBILITY: 'PRIVATE',
    DEFAULT_PHONE_VISIBILITY: 'PRIVATE',
    DEFAULT_LOCATION_VISIBILITY: 'FRIENDS',
    DEFAULT_DOB_VISIBILITY: 'FRIENDS',
    DEFAULT_FRIEND_REQUEST_PERMISSION: 'EVERYONE',
    DEFAULT_MESSAGE_PERMISSION: 'FRIENDS',
  },

  // Search
  SEARCH: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 10,
    MAX_LIMIT: 100,
    MIN_QUERY_LENGTH: 2,
  },
} as const;

// Type exports
export type VisibilityType = 'PUBLIC' | 'FRIENDS' | 'FRIENDS_OF_FRIENDS' | 'ONLY_ME' | 'PRIVATE' | 'EVERYONE' | 'CUSTOM';